# Generated by Django 4.1.3 on 2024-03-16 06:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/', validators=[api.models.validate_image]),
        ),
        migrations.AddField(
            model_name='product',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
